### ISSUE TITLE
Titles on exercice pages

### ISSUE THREAD

**Issue by bencobenki** [ECAM-Brussels/e-cam#4]
Ce serait pratique de pouvoir donner un titre à chaque page d'exercices d'entraînement, et de voir le chemin.
P.e. Algèbre > Factorisation 2ème degré > Facile

**Comment by khoi-nguyen** [comment]
On peut maintenant ajouter `title: 'Titre'` dans les séquences d'exercices

**Comment by khoi-nguyen** [comment]
J'ai ajouté un title à toutes les séquences
